name: ctrlx-diagnostics-app
version: 2.6.0
summary: Webserver UI to register and unregister Diagnostics.
title: ctrlx-diagnostics-app
description: |
  Web server user interface to create JSON files from CSV data containing diagnostics information that can be registered and unregistered via DataLayer. 
base: core22
confinement: strict
grade: stable
architectures:
   - build-on: [amd64]
     build-for: [arm64]  ### <------ CHANGE IF NEEDED

apps:
  webserver:
    command: bin/main.py
    plugs:
      - network
      - network-bind
      - datalayer
      - active-solution
    slots:
      - package-assets
      - package-run
    daemon: simple
    restart-condition: always
    passthrough:   
      restart-delay: 10s

parts:
  webserver:
    plugin: python
    source: .
    source-type: local
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

  custom-deps1:
    plugin: dump
    source: /usr/lib/aarch64-linux-gnu 
    source-type: local
    organize:
      "*": "usr/lib/aarch64-linux-gnu/"

  templates:
    plugin: dump
    source: ./templates
    organize:
      '*': templates/

  static:
    plugin: dump
    source: ./static
    organize:
      '*': static/

  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
        - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer

  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions
